baseurl:
timezone: Europe/Berlin
permalink: /:categories/:year/:month/:day/:title
paginate: 9
markdown: kramdown
kramdown:
    input: GFM
    extensions:
        - autolink
        - footnotes
        - smart
        - hard_wrap
        - no_intra_emphasis
        - strikethrough
        - tables
        - lax_spacing
        - with_toc_data
highlighter: rouge
excerpt_separator:

#gems: [jekyll-paginate]