baseURL = "https://demo.soranoiseki.com/"
theme = "skynova"
enableRobotsTXT = true 

# Set the default content language
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false

# Global parameters
# In each language, the title, description, and keywords can be overridden
[params]
author = "Max Mustermann"
noIndex = true


# Languages configuration
[languages]

## Deutsch (default)

[languages.de]
weight = 0
disabled = false
languageName = "Deutsch"
languageCode = "de-DE"
title = "IsekiFrame"

[languages.de.params]
description = "Ein Beispiel für eine mehrsprachige Website"
keywords = "Hugo, Website, Multilingual"

[languages.de.permalinks]
posts = "/neuigkeiten/:slug/"

[[languages.de.menus.main]]
name = "Startseite"
pageRef = "/"
weight = 10

[[languages.de.menus.main]]
name = "Neuigkeiten"
pageRef = "/posts"
weight = 20

[[languages.de.menus.main]]
name = "Tags"
pageRef = "/tags"
weight = 30

[[languages.de.menus.main]]
name = "Kontakt"
pageRef = "/contact"
weight = 40


## English

[languages.en]
weight = 1
disabled = false
languageName = "English"
languageCode = "en-US"
title = "IsekiFrame"

[languages.en.params]
description = "Ein Beispiel für eine mehrsprachige Website."
keywords = "Hugo, Website, Multilingual"

[languages.en.permalinks]
posts = "/news/:slug/"

[[languages.en.menus.main]]
name = "Home"
pageRef = "/"
weight = 10

[[languages.en.menus.main]]
name = "News"
pageRef = "/posts"
weight = 20

[[languages.en.menus.main]]
name = "Tags"
pageRef = "/tags"
weight = 30

[[languages.en.menus.main]]
name = "Contact"
pageRef = "/contact"
weight = 40


## Chinese (Simplified)

[languages.zh]
weight = 2
disabled = false
languageName = "简体中文"
languageCode = "zh-CN"
title = "IsekiFrame"

[languages.zh.params]
description = "一个多语言网站的示例"
keywords = "Hugo, 网站, 多语言"

[languages.zh.permalinks]
posts = "/news/:slug/"

[[languages.zh.menus.main]]
name = "主页"
pageRef = "/"
weight = 10

[[languages.zh.menus.main]]
name = "近期动态"
pageRef = "/posts"
weight = 20

[[languages.zh.menus.main]]
name = "联系方式"
pageRef = "/contact"
weight = 40


## Chinese (Traditional)

[languages.tc]
weight = 3
disabled = false
languageName = "繁體中文"
languageCode = "zh-TW"
title = "IsekiFrame"

[languages.tc.params]
description = "一個多語言網站的示例"
keywords = "Hugo, 網站, 多語言"

[languages.tc.permalinks]
posts = "/news/:slug/"

[[languages.tc.menus.main]]
name = "主頁"
pageRef = "/"
weight = 10

[[languages.tc.menus.main]]
name = "聯繫方式"
pageRef = "/contact"
weight = 40
